name: GCP-VM-CICD

on:
  push: 
    branches: [deploy-jo, deploy-jh, deploy-hj, deploy-wr]
  pull_request: 
    branches: [deploy-jo, deploy-jh, deploy-hj, deploy-wr]

jobs:
  build-deploy-florography:
    runs-on: ubuntu-22.04
    steps:  
      - name: "환경변수 세팅"
        run: |
          if [ ${{github.ref}} == 'refs/heads/deploy-jo' ]; then
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_JO}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_JO}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.GCP_VM_SSHKEY_JO }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_JO}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_JO}}" >> $GITHUB_ENV
            echo "EVN_PRODUCTION=${{secrets.ENV_PRODUCTION_JO}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_JO}}" >> $GITHUB_ENV
          
          elif [ ${{github.ref}} == 'refs/heads/deploy-jh' ]; then
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_JH}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_JH}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.GCP_VM_SSHKEY_JH }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_JH}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_JH}}" >> $GITHUB_ENV
            echo "EVN_PRODUCTION=${{secrets.EVN_PRODUCTION_JH}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_JH}}" >> $GITHUB_ENV
          
          elif [ ${{github.ref}} == 'refs/heads/deploy-hj' ]; then
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_HJ}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_HJ}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.GCP_VM_SSHKEY_HJ }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_HJ}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_HJ}}" >> $GITHUB_ENV
            echo "EVN_PRODUCTION=${{secrets.EVN_PRODUCTION_HJ}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_HJ}}" >> $GITHUB_ENV
          
          elif [ ${{github.ref}} == 'refs/heads/deploy-wr' ]; then
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_WR}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_WR}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.GCP_VM_SSHKEY_WR }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_WR}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_WR}}" >> $GITHUB_ENV
            echo "EVN_PRODUCTION=${{secrets.EVN_PRODUCTION_WR}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_WR}}" >> $GITHUB_ENV
            
          fi
            
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GCP_VM_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 검증
          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Invalid key format"
          
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{github.ref}}

      - name: Springboot Build and Docker image build and push
        run: |
          echo ${{env.EVN_PRODUCTION}} | base64 --decode > C:\project\florography-web\.env.production
          echo "${{env.DOCKER_PASSWORD}}" | docker login -u ${{env.DOCKER_USERNAME}} --password-stdin
          
          docker build -t ${{env.DOCKER_USERNAME}}/spring-app:latest .
          docker push ${{env.DOCKER_USERNAME}}/spring-app:latest

      - name: GCP SSH REMOTE 원격접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.GCP_VM_HOST}}
          username: ${{env.GCP_VM_USERNAME}}
          key: ${{env.GCP_VM_SSHKEY}}
          script: |
            cd /home/${{env.GCP_VM_USERNAME}}
            sudo docker compose -f api-docker-compose.yaml pull
            sudo docker compose -f api-docker-compose.yaml down
            sudo docker compose -f api-docker-compose.yaml up -d
